version: "2.2"
services:
  mdujiaoka:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=127.0.0.1 client_port=9003 start_with_request=yes
      XDEBUG_SESSION: 1
    volumes:
      - ..:/mateqq_apps/mdujiaoka
    depends_on:
      - mdujiaoka-db
      - mdujiaoka-redis

  mdujiaoka-db:
    image: mysql:8.0-debian
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=mdujiaoka
      - MYSQL_ROOT_PASSWORD=123456
    # port 3306 is exposed by default, so there is no need to do it again here

  mdujiaoka-redis:
    image: redis:7.0.11

  mdujiaoka-deploy:
    image: charliechen102/mautodeploy:latest

  mdujiaoka-adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - mdujiaoka-db

networks:
  default:
    name: mate
    external: true

