version: "2.2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - internal
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=127.0.0.1 client_port=9003 start_with_request=yes
      XDEBUG_SESSION: 1
    volumes:
      - ..:/mateqq_apps/mdujiaoka
    depends_on:
      - db
      - redis

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ..:/mateqq_apps/mdujiaoka
    depends_on:
      - web

  db:
    image: mysql:8.0-debian
    networks:
      - internal
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=mdujiaoka
      - MYSQL_ROOT_PASSWORD=123456
    # port 3306 is exposed by default, so there is no need to do it again here

  redis:
    image: redis:7.0.11
    networks:
      - internal

  adminer:
    image: adminer
    networks:
      - internal
    ports:
      - 8081:8080
    depends_on:
      - db

networks:
  internal:
    driver: bridge

